raytracer:
	g++ -Iinclude -Iinclude/HLSL -o raytracer src/*.cpp src/Raytracer/*.cpp src/Raytracer/Objects/*.cpp src/Raytracer/Scenes/*.cpp

.PHONY: raytracer

clean:
	rm -f raytracer
	rm -f image.bmp
	
